### PR TITLE
Added pronunciation note

### PR DESCRIPTION
**Pull request by joelmartinez**

### CODE REVIEW

**Comment by popthestack** [comment]
no

no

no

no

nope

nope

nope

**Comment by popthestack** [comment]
colbert no

**Comment by adamweeks** [comment]
meh

**Comment by adamweeks** [comment]
ha

**Comment by popthestack** [comment]
welp

you are wrong

oh well

**Comment by adamweeks** [comment]
I've been wrong before. I will be wrong again.

**Comment by joelmartinez** [comment]
There there

**Comment by popthestack** [comment]
aint bothered

**Comment by popthestack** [comment]
In case you thought I'd forgotten, this was a terrible jit commit.

mic drop

**Pull request merged**
